### ISSUE TITLE
tk#1_git

### ISSUE THREAD

**Issue by Gona79** [ISPC-TST-PI-I-2024/proyecto-final-capa-de-percepcion-grupo-2#2]
# issue 1: tk#1_git

## Investigar sobre el uso de git  y github 

1) Crear documentacion sobre git siguiendo el siguiente contenido. 

git: init, add, commit, checkout, branch, merge , push, pull, fetch  (revert, show, diff, ...tag)

**Comment by RiosLionel** [comment]
¿Que es Git y GitHub?

Git es un sistema de control de versiones de los archivos creados. Git realiza seguimiento de cambios, llevando un registro de lo trabajado posibilitando volver a una version anterior. 

GitHub, es Git en linea, o repositorio en la nube. Facilitando el trabajo con grupos de personas trabajando todas sobre un mismo proyecto.

¿Cuales son los comandos de Git y GitHub?

Cualquiera de las dos herramientas, posee o utiliza los mismos comandos.

Comandos para configuracion de repositorio

	Git config (primeramente configuramos nombre y mail)

	Git init (incializa el repositorio,creando un subdirectorio .git)

	Git clone (clonar un repositorio local o remoto) 

Comandos para cambios

	Git add . (mueve los cambios realizados en el directorio local a la rama)

	Git commit (confirma los cambios, y agrega un mensaje de aviso)

	Git status (muestra si existe algun cambio o archivo sin seguimiento)

	Git diff (para comparar dos conjunto de datos, se usa junto a git status y git log)

	Git stash (almacena temporalmente los cambios sin corfirmar)

Comandos examen repositorio

	Git tag (crea una nueva etiqueta)
	
	Git blame (Visualizar los metadatos de Autor adjuntos)

Comandos para deshacer cambios

	Git clean (para deshacer cambios de archivos sin seguimiento)

	Git revert (invierte los cambios realizados al confirmar seguimiento)

	Git reset (deshace cambios, de 3 formas distintas soft, mixed y hard)

	Git rm (elimina archivos sueltos o dejar de seguir algun archivo)

Comandos creacion de ramas y unificacion

	Git Branch (son las ramas de trabajo)

	Git Merge (permite tomar las ramas o lineas, y unificarlas)

	Git Checkout (Permite ver los cambios de las ramas creadas por Git branch)

Comandos sincronizacion remota

	Git Fetch (descarga confirmaciones, archivos y referencias de un repositorio remoto a tu repositorio local)

	Git Push (Cargar contenido de un repositorio local a uno remoto)

	Git Pull (traer y combinar repositorios remotos, reorganizandolos)

### https://www.atlassian.com/es/git/tutorials
### https://git-scm.com/doc

**Comment by RiosLionel** [comment]
![Image](https://github.com/ISPC-TST-PI-I-2024/proyecto-final-capa-de-percepcion-grupo-2/assets/108525591/53ea145c-247b-43eb-95d1-69ed7f01595f)
